import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="LsbL9cyV3LVsVU9It50Ln-X0OrVnTOw_e6MCoM4mAkw"
        />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Vatro Visuals" />
        {/* Preload SVG logo for instant display */}
        <link
          rel="preload"
          as="image"
          href="/Logo%20Merged.svg"
          type="image/svg+xml"
        />
        {/* ...other meta tags... */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-font`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
